package trabalho.lfa;

import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;

/**
 *
 *@author João Favero e Thalys Marques
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        txtDesc = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        txtSent = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtSaida = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        jPanel4.setLayout(new java.awt.GridLayout(1, 3));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "a", "b", "c", "d", "e", "f", "g", "h", "i", "j" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createTitledBorder("Automato"));
        jComboBox1.setMaximumSize(null);
        jComboBox1.setMinimumSize(null);
        jComboBox1.setPreferredSize(new java.awt.Dimension(400, 300));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox1);

        jPanel2.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(1, 2));

        txtDesc.setEditable(false);
        txtDesc.setText("L1 = { começa com ae termina com b }");
        txtDesc.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição"));
        jPanel5.add(txtDesc);

        jPanel2.add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        txtSent.setBorder(javax.swing.BorderFactory.createTitledBorder("Sentença"));
        txtSent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSentActionPerformed(evt);
            }
        });
        jPanel6.add(txtSent);

        jPanel2.add(jPanel6);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        txtSaida.setEditable(false);
        txtSaida.setText("sentença reconhecida");
        txtSaida.setBorder(javax.swing.BorderFactory.createTitledBorder("Saída"));
        jPanel3.add(txtSaida);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jButton2.setText("Executar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2);

        jButton3.setText("Limpar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3);

        jButton.setText("Sobre");
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });
        jPanel7.add(jButton);

        jPanel3.add(jPanel7);

        jPanel1.add(jPanel3, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String descricao = "L1 = { ";
            char a = jComboBox1.getSelectedItem().toString().charAt(0);
            switch (a) {
                case 'a':
                    descricao += "começa com ae termina com b }";
                    break;
                case 'b':
                    descricao += "possui aaa como subcadeia }";
                    break;
                case 'c':
                    descricao += "possui baba como prefixo e abab como sufixo }";
                    break;
                case 'd':
                    descricao += "possui no máximo uma ocorrência da cadeia baba }";
                    break;
                case 'e':
                    descricao += "não possui ocorrência da cadeia baba }";
                    break;
                case 'f':
                    descricao += "possui ocorrência par de a's seguida por ocorrência impar de b's }";
                    break;
                case 'g':
                    descricao += "começa com a e possui ocorrência par de a's ou começa com b e possui ocorrência impar de b's }";
                    break;
                case 'h':
                    descricao += "inicia-se com 0e a soma de todos os seus dígitosé par, ou inicia-se com 1e a soma de todos os seus dígitos é impar }";
                    break;
                case 'i':
                    descricao += "inicia-se com uma letra, possuindo a seguir qualquer combinação de letras e dígitos }";
                    break;
                case 'j':
                    descricao += "é um número inteiro, um número decimal ou um número representado em notação científica }";
                    break;
            }
            txtDesc.setText(descricao);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if ("".equals(txtSent.getText())) {
            JOptionPane.showMessageDialog(this,"Insira uma sentença primeiro!!!");
        } else {
            switch (jComboBox1.getSelectedItem().toString().charAt(0)) {
                case 'a':
                    txtSaida.setText(Automatos.A(txtSent.getText()));
                    break;
                case 'b':
                    txtSaida.setText(Automatos.B(txtSent.getText()));
                    break;
                case 'c':
                    txtSaida.setText(Automatos.C(txtSent.getText()));
                    break;
                case 'd':
                    txtSaida.setText(Automatos.D(txtSent.getText()));
                    break;
                case 'e':
                    txtSaida.setText(Automatos.E(txtSent.getText()));
                    break;
                case 'f':
                    txtSaida.setText(Automatos.F(txtSent.getText()));
                    break;
                case 'g':
                    txtSaida.setText(Automatos.G(txtSent.getText()));
                    break;
                case 'h':
                    txtSaida.setText(Automatos.H(txtSent.getText()));
                    break;
                case 'i':
                    txtSaida.setText(Automatos.I(txtSent.getText()));
                    break;
                case 'j':
                    txtSaida.setText(Automatos.J(txtSent.getText()));
                    break;
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        txtSent.setText("");
        txtSaida.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtSentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSentActionPerformed

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Feito por João Favero e Thalys Marques","Sobre",JOptionPane.DEFAULT_OPTION);
        
    }//GEN-LAST:event_jButtonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtSaida;
    private javax.swing.JTextField txtSent;
    // End of variables declaration//GEN-END:variables
}
